### ISSUE TITLE
关于本地储存方案

### ISSUE THREAD

**Issue by chenstarx** [lzq920/toy-maker#1]
你好，我注意到本项目中一开始使用了 GoDB，但后来切换为了 jsstore，因此想了解一下这么做的原因，从而帮助我改进 GoDB，谢谢！

**Comment by lzq920** [comment]
@chenstarx  GoDB很棒，在做单个表存储的时候特别简洁方便,jsstore的话，我更加看重它本身提供的更多高阶方法吧，提供了更多的类似SQL的操作

**Comment by chenstarx** [comment]
噢噢，谢谢回复。就是说如果 GoDB 有更多高阶方法的话，会更方便使用

**Comment by lzq920** [comment]
是的，没错！现在GoDB够用，但在部分业务场景的时候还需要再扩展一下

发自我的iPhone
